BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test" 
TRAIN:
  BATCH_SIZE: 10
  EPOCHS: 30
  LR: 9e-3
  MODEL_FILE_NAME: deepphys
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: Private_dataset
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/media/super_fast_storage/matthieu_scherpf/_tmp/segments"                   # Raw dataset path, need to be updated
    CACHED_PATH: "/media/super_fast_storage_2/matthieu_scherpf/_tmp/rppg_toolbox/datasets"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      USE_PSUEDO_PPG_LABEL: False
      DATA_TYPE: ['DiffNormalized','Standardized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 61
      CROP_FACE:
        DO_CROP_FACE: False
        BACKEND: null    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: False
        LARGE_BOX_COEF: null
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : null
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
VALID:
  DATA:
    FS: 30
    DATASET: BP4DPlus_custom
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/media/super_fast_storage/matthieu_scherpf/_tmp/segments"                   # Raw dataset path, need to be updated
    CACHED_PATH: "/media/super_fast_storage_2/matthieu_scherpf/_tmp/rppg_toolbox/datasets"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      USE_PSUEDO_PPG_LABEL: False
      DATA_TYPE: ['DiffNormalized','Standardized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 610
      CROP_FACE:
        DO_CROP_FACE: False
        BACKEND: null    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: False
        LARGE_BOX_COEF: null
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : null
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: True                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: BP4DPlus_custom # BP4DPlus_custom, PURE_custom, UBFC-rPPG_custom
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/media/super_fast_storage/matthieu_scherpf/_tmp/segments"                   # Raw dataset path, need to be updated
    CACHED_PATH: "/media/super_fast_storage_2/matthieu_scherpf/_tmp/rppg_toolbox/datasets"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      USE_PSUEDO_PPG_LABEL: False
      DATA_TYPE: ['DiffNormalized','Standardized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 61
      CROP_FACE:
        DO_CROP_FACE: False
        BACKEND: null    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: False
        LARGE_BOX_COEF: null
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : null
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: /media/super_fast_storage_2/matthieu_scherpf/_tmp/rppg_toolbox/exp_logs
MODEL:
  DROP_RATE: 0.2
  NAME: DeepPhys
INFERENCE:
  BATCH_SIZE: 1
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH: "/media/super_fast_storage_2/matthieu_scherpf/_tmp/rppg_toolbox/exp_logs/Private_dataset_SizeW72_SizeH72_ClipLength61_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceFalse_BackendNone_Large_boxFalse_Large_sizeNone_Dyamic_DetFalse_det_lenNone_Median_face_boxFalse/PreTrainedModels/deepphys_valid_loss_Epoch29.pth"
